### ISSUE TITLE
Using uMurmur as server

### ISSUE THREAD

**Issue by joaofauvel** [pzmarzly/mic_over_mumble#13]
I run Arch and murmur-server is only available through the AUR. I have already made the modifications necessary to use umurmur on my fork, the only annoyance are the certificate issues. Would it be possible to implement umurmur capability here?

**Comment by pzmarzly** [comment]
> murmur-server is only available through the AUR

It is available in the normal repos, under the name [`murmur`](https://archlinux.org/packages/community/x86_64/murmur/)

> certificate issues

Sadly, I've never used [umurmur](https://github.com/umurmur/umurmur) or even murmur with SSL enabled, so I don't know anything about certificate issues you are experiencing. But if you have time and willingness to describe them here, then I'll try to investigate.

**Comment by joaofauvel** [comment]
Not sure how I missed that... The only reason I wanted umurmur to work was convenience, but since murmur is available it's a moot issue.
