### ISSUE TITLE
Should display the server's IP in the terminal

### ISSUE THREAD

**Issue by vankomerzhic24** [pzmarzly/mic_over_mumble#17]
For me it's not static so I have to look it up in the router's menu every time I want to connect. Plus, some people don't even remember their login and password for it.

**Comment by pzmarzly** [comment]
Please check if the code I just wrote in #18 works for you (you can download the whole file [by this link](https://raw.githubusercontent.com/pzmarzly/mic_over_mumble/b678355426c46c00ee3a8faf63e8089d40c2d59d/mic_over_mumble)).

**Comment by vankomerzhic24** [comment]
Here's what it says:

```
Starting Mumble server (murmurd)...
Starting Mumble client (a window should appear in a moment)...
Changing PulseAudio configuration...
Adding sink...
Adding a virtual microphone...
Done. Please use pavucontrol to ensure everything works.
Skipping IP printing: jq command not found...
Press Return to shut down...
```
And I'm using Ubuntu 20.04.2 LTS x86_64

**Comment by pzmarzly** [comment]
Oh, I thought that `jq` is installed by default on Ubuntu, but it turns out I had it installed because of `playonlinux`. Could you try running `sudo apt install jq` and then running the script again?

**Comment by vankomerzhic24** [comment]
Yes, now it shows. Are you planning on adding `jq` to the dependencies or using some other approach that doesn't require one?

**Comment by pzmarzly** [comment]
For now I plan to add `jq` as optional dependency (the rest of the script will work without it, and I'll put a note in README). But if https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/812 is resolved (e.g. by https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/497 being merged), I'll consider rewriting all the parsing logic to `jq`, as it's much more likely not to break in the future and in weird configurations (see #5) plus it should make the code much more readable. However, I'm open to any suggestions about that idea.
