### ISSUE TITLE
pipewire script?

### ISSUE THREAD

**Issue by ghost** [pzmarzly/mic_over_mumble#24]
im using pipewire-pulse and the script doesnt works, i was trying converting the script to pactl commands but idk much about scripting, ill be grateful if you can do something to be compatible with pipewire-pulse cuz pacmd command doesnt exists here :/ thankss
[mic_over_mumble_pipewire](https://github.com/pzmarzly/mic_over_mumble/files/7231574/mic_over_mumble.log)
,

**Comment by siddhpant** [comment]
I made one. Have a look at https://github.com/siddhpant/broo.

**Comment by pzmarzly** [comment]
I merged #21 which should help. Also put broo in the readme as an alternative
